#!/bin/bash
ROOT=$1
PREFIX=$2
cd $ROOT
export CC="/opt/rh/devtoolset-1.1/root/usr/bin/gcc"
export CXX="/opt/rh/devtoolset-1.1/root/usr/bin/g++"
export CFLAGS="-fPIC"
export CXXFLAGS="-fPIC -std=c++11"
export LDFLAGS="-fPIC -std=c++11"
export HDF_ROOT=/tmp/VFXREFPLAT/BUILDS/CY2015/hdf5/1.8.14
cmake -D CMAKE_INSTALL_PREFIX=$PREFIX \
-D BOOST_ROOT=/tmp/VFXREFPLAT/BUILDS/CY2015/boost/1.55.0 \
-D ILMBASE_ROOT=/tmp/VFXREFPLAT/BUILDS/CY2015/ilmbase/2.2.0 \
-D ALEMBIC_ILMBASE_HALF_LIB=/tmp/VFXREFPLAT/BUILDS/CY2015/ilmbase/2.2.0/lib/libHalf.a \
-D ALEMBIC_ILMBASE_IEX_LIB=/tmp/VFXREFPLAT/BUILDS/CY2015/ilmbase/2.2.0/lib/libIex.a \
-D ALEMBIC_ILMBASE_ILMTHREAD_LIB=/tmp/VFXREFPLAT/BUILDS/CY2015/ilmbase/2.2.0/lib/libIlmThread.a \
-D ALEMBIC_ILMBASE_IMATH_LIB=/tmp/VFXREFPLAT/BUILDS/CY2015/ilmbase/2.2.0/lib/libImath.a \
-D ALEMBIC_PYILMBASE_PYIMATH_LIB=/tmp/VFXREFPLAT/BUILDS/CY2015/ilmbase/2.2.0/lib/libPyImath.so \
-D ALEMBIC_PYILMBASE_INCLUDE_DIRECTORY=/tmp/VFXREFPLAT/BUILDS/CY2015/ilmbase/2.2.0/include \
-D ALEMBIC_PYILMBASE_PYIMATH_MODULE=/tmp/VFXREFPLAT/BUILDS/CY2015/ilmbase/2.2.0/lib/python2.7/site-packages/imathmodule.so \
-D HDF_ROOT=/tmp/VFXREFPLAT/BUILDS/CY2015/hdf5/1.8.14 \
-D HDF5_DIR=/tmp/VFXREFPLAT/BUILDS/CY2015/hdf5/1.8.14 \
-D HDF5_INCLUDE_DIR=/tmp/VFXREFPLAT/BUILDS/CY2015/hdf5/1.8.14/include \
-D HDF5_INCLUDE_DIR=/tmp/VFXREFPLAT/BUILDS/CY2015/hdf5/1.8.14/include \
-D HDF5_hdf5_LIBRARY_RELEASE=/tmp/VFXREFPLAT/BUILDS/CY2015/hdf5/1.8.14/lib/libhdf5.a \
-D HDF5_hdf5_hl_LIBRARY_RELEASE=/tmp/VFXREFPLAT/BUILDS/CY2015/hdf5/1.8.14/lib/libhdf5_hl.a \
-D ALEMBIC_PYTHON_ROOT=/tmp/VFXREFPLAT/BUILDS/CY2015/python/2.7.9 \
-D PYTHON_INCLUDE_DIR=/tmp/VFXREFPLAT/BUILDS/CY2015/python/2.7.9/include/python2.7 \
-D ALEMBIC_PYTHON_LIBRARY=/tmp/VFXREFPLAT/BUILDS/CY2015/python/2.7.9/lib/libpython2.7.so \
-D LIBPYTHON_VERSION="2.7" ..