#!/bin/bash
mkdir -p $ROOT/BUILD
cd $ROOT/BUILD
export CFLAGS="-fPIC -std=c++11 -DALEMBIC_LIB_USES_BOOST"
export CXXFLAGS="-fPIC -std=c++11 -DALEMBIC_LIB_USES_BOOST"
export LDFLAGS="-fPIC"
cmake -D CMAKE_INSTALL_PREFIX=$PREFIX \
-D BOOST_ROOT=${BOOST_PREFIX} \
-D ILMBASE_ROOT=${ILMBASE_PREFIX} \
-D ALEMBIC_ILMBASE_HALF_LIB=${ILMBASE_PREFIX}/lib/libHalf.a \
-D ALEMBIC_ILMBASE_IEX_LIB=${ILMBASE_PREFIX}/lib/libIex.a \
-D ALEMBIC_ILMBASE_ILMTHREAD_LIB=${ILMBASE_PREFIX}/lib/libIlmThread.a \
-D ALEMBIC_ILMBASE_IMATH_LIB=${ILMBASE_PREFIX}/lib/libImath.a \
-D ALEMBIC_PYILMBASE_PYIMATH_LIB=${ILMBASE_PREFIX}/lib/libPyImath.so \
-D ALEMBIC_PYILMBASE_INCLUDE_DIRECTORY=${ILMBASE_PREFIX}/include \
-D ALEMBIC_PYILMBASE_PYIMATH_MODULE=${ILMBASE_PREFIX}/lib/python2.7/site-packages/imathmodule.so \
-D HDF5_ROOT=${HDF5_PREFIX} \
-D HDF5_DIR=${HDF5_PREFIX} \
-D HDF5_INCLUDE_DIR=${HDF5_PREFIX}/include \
-D HDF5_INCLUDE_DIR=${HDF5_PREFIX}/include \
-D HDF5_hdf5_LIBRARY_RELEASE=${HDF5_PREFIX}/lib/libhdf5.a \
-D HDF5_hdf5_hl_LIBRARY_RELEASE=${HDF5_PREFIX}/lib/libhdf5_hl.a \
-D ALEMBIC_PYTHON_ROOT=${PYTHON_PREFIX} \
-D PYTHON_INCLUDE_DIR=${PYTHON_PREFIX}/include/python2.7 \
-D ALEMBIC_PYTHON_LIBRARY=${PYTHON_PREFIX}/lib/libpython2.7.so \
-D LIBPYTHON_VERSION="2.7" ..;
make
make install

mv $PREFIX/alembic-1.5.8/* $PREFIX/
rm -rf $PREFIX/alembic-1.5.8

