#!/bin/bash

mkdir -p $ROOT/BUILD
cd $ROOT/BUILD

cmake -D CMAKE_CXX_FLAGS="-fPIC" -D CMAKE_INSTALL_PREFIX=${PREFIX} -DBOOST_ROOT=${BOOST_PREFIX} -DILMBASE_HOME=${ILMBASE_PREFIX} -DOPENEXR_HOME=${OPENEXR_PREFIX} -DPYTHON=${PYTHON_PREFIX}/bin/python -DPYTHON_VERSION=2.7 -DOCIO_HOME=${OCIO_PREFIX} ..
make 
make install