#!/bin/bash
cd $ROOT/openvdb

make install \
DESTDIR="${DESTDIR}" \
BOOST_INCL_DIR="${BOOST_INCL_DIR}" \
BOOST_LIB_DIR="${BOOST_LIB_DIR}" \
BOOST_LIB="${BOOST_LIB}" \
BOOST_THREAD_LIB="${BOOST_THREAD_LIB}" \
EXR_INCL_DIR="${EXR_INCL_DIR}" \
EXR_LIB_DIR="${EXR_LIB_DIR}" \
ILMBASE_INCL_DIR="${ILMBASE_INCL_DIR}" \
ILMBASE_LIB_DIR="${ILMBASE_LIB_DIR}" \
BLOSC_INCL_DIR="${BLOSC_INCL_DIR}" \
TBB_INCL_DIR="${TBB_INCL_DIR}" \
TBB_LIB_DIR="${TBB_LIB_DIR}" \
TBB_LIB="${TBB_LIB}" \
CONCURRENT_MALLOC_LIB="${CONCURRENT_MALLOC_LIB}" \
CONCURRENT_MALLOC_LIB_DIR="${CONCURRENT_MALLOC_LIB_DIR}" \
CPPUNIT_INCL_DIR="${CPPUNIT_INCL_DIR}" \
LOG4CPLUS_INCL_DIR="${LOG4CPLUS_INCL_DIR}" \
GLFW_INCL_DIR="${GLFW_INCL_DIR}" \
PYTHON_VERSION="${PYTHON_VERSION}" \
PYTHON_INCL_DIR="${PYTHON_INCL_DIR}" \
PYTHON_LIB_DIR="${PYTHON_LIB_DIR}" \
PYTHON_LIB="${PYTHON_LIB}" \
BOOST_PYTHON_LIB_DIR="${BOOST_PYTHON_LIB_DIR}" \
BOOST_PYTHON_LIB="${BOOST_PYTHON_LIB}" \
NUMPY_INCL_DIR="${NUMPY_INCL_DIR}" \
EPYDOC="${EPYDOC}" \
DOXYGEN="${DOXYGEN}"