#!/bin/bash

mkdir -p $ROOT/BUILD
cd $ROOT/BUILD

cmake -D CMAKE_CXX_FLAGS="-fPIC" -D CMAKE_INSTALL_PREFIX=${PREFIX} -D PYTHON=${PYTHON_PREFIX}/bin/python -D OCIO_BUILD_APPS=$OCIO_BUILD_APPS -D OCIO_BUILD_SHARED=$OCIO_BUILD_SHARED -D OIIO_PATH=${OIIO_PREFIX} ..
make 
make install